export const OFFICIAL_DOMAINS: Record<string, string[]> = {
  paypal: ["paypal.com", "paypal.me", "paypalobjects.com"],
  apple: ["apple.com", "icloud.com", "me.com", "appleid.com"],
  google: [
    "google.com",
    "google.co.in",
    "google.co.uk",
    "youtube.com",
    "gmail.com",
    "android.com",
    "googleusercontent.com",
    "gstatic.com",
    "withgoogle.com",
  ],
  microsoft: [
    "microsoft.com",
    "office.com",
    "live.com",
    "outlook.com",
    "xbox.com",
    "microsoftonline.com",
    "office365.com",
    "onedrive.com",
    "windows.com",
    "msn.com",
    "bing.com",
  ],
  amazon: [
    "amazon.com",
    "amazon.in",
    "amazon.co.uk",
    "amazon.de",
    "amazon.ca",
    "amazon.co.jp",
    "amazonaws.com",
    "a2z.com",
  ],
  meta: [
    "facebook.com",
    "fb.com",
    "instagram.com",
    "whatsapp.com",
    "wa.me",
    "messenger.com",
    "meta.com",
    "threads.net",
  ],
  netflix: ["netflix.com"],
  spotify: ["spotify.com"],
  x: ["x.com", "twitter.com", "t.co"],
  linkedin: ["linkedin.com", "lnkd.in"],
  steam: ["steampowered.com", "steamcommunity.com"],
  binance: ["binance.com"],
  coinbase: ["coinbase.com"],
  metamask: ["metamask.io"],
  adobe: ["adobe.com"],
  dropbox: ["dropbox.com"],
  dhl: ["dhl.com"],
  fedex: ["fedex.com"],
  ups: ["ups.com"],
  usps: ["usps.com"],
  indiapost: ["indiapost.gov.in"],
  sbi: ["onlinesbi.sbi", "sbi.co.in", "sbi.com"],
  hdfc: ["hdfcbank.com"],
  icici: ["icicibank.com"],
  axis: ["axisbank.com"],
  kotak: ["kotak.com", "kotakbank.com"],
  paytm: ["paytm.com", "paytmbank.com"],
  phonepe: ["phonepe.com"],
  bhim: ["bhimupi.org.in"],
  npci: ["npci.org.in"],
  irctc: ["irctc.co.in"],
  uidai: ["uidai.gov.in"],
  incometax: ["incometax.gov.in"],
  cybercrime: ["cybercrime.gov.in"],
  rbi: ["rbi.org.in"],
  govin: ["india.gov.in", "gov.in"],
  irs: ["irs.gov"],
  ssa: ["ssa.gov"],
  ftc: ["ftc.gov"],
  ic3: ["ic3.gov"],
  chase: ["chase.com"],
  bofa: ["bankofamerica.com"],
  wellsfargo: ["wellsfargo.com"],
  citi: ["citi.com", "citibank.com"],
  capitalone: ["capitalone.com"],
};

export const BRAND_ALIASES: Record<string, string> = {
  paypal: "paypal",
  apple: "apple",
  icloud: "apple",
  appleid: "apple",
  google: "google",
  gmail: "google",
  youtube: "google",
  microsoft: "microsoft",
  outlook: "microsoft",
  office365: "microsoft",
  office: "microsoft",
  hotmail: "microsoft",
  xbox: "microsoft",
  amazon: "amazon",
  awsprize: "amazon",
  facebook: "meta",
  instagram: "meta",
  insta: "meta",
  whatsapp: "meta",
  messenger: "meta",
  meta: "meta",
  netflix: "netflix",
  spotify: "spotify",
  twitter: "x",
  linkedin: "linkedin",
  steam: "steam",
  binance: "binance",
  coinbase: "coinbase",
  metamask: "metamask",
  adobe: "adobe",
  dropbox: "dropbox",
  dhl: "dhl",
  fedex: "fedex",
  ups: "ups",
  usps: "usps",
  sbi: "sbi",
  hdfc: "hdfc",
  hdfcbank: "hdfc",
  icici: "icici",
  icicibank: "icici",
  axis: "axis",
  axisbank: "axis",
  kotak: "kotak",
  paytm: "paytm",
  phonepe: "phonepe",
  bhim: "bhim",
  irctc: "irctc",
  aadhaar: "uidai",
  aadhar: "uidai",
  uidai: "uidai",
  incometax: "incometax",
  chase: "chase",
  wellsfargo: "wellsfargo",
  bankofamerica: "bofa",
  citibank: "citi",
  capitalone: "capitalone",
  irs: "irs",
};

export const SUSPICIOUS_TLDS = new Set([
  "xyz",
  "tk",
  "ml",
  "ga",
  "cf",
  "gq",
  "top",
  "click",
  "zip",
  "mov",
  "country",
  "stream",
  "gdn",
  "loan",
  "win",
  "bid",
  "review",
  "account",
  "download",
  "cfd",
  "sbs",
  "cyou",
  "icu",
  "rest",
  "support",
  "help",
  "security",
  "finance",
  "quest",
  "work",
  "cam",
  "buzz",
  "club",
  "info",
]);

export const SHORTENERS = new Set([
  "bit.ly",
  "tinyurl.com",
  "t.co",
  "goo.gl",
  "ow.ly",
  "is.gd",
  "buff.ly",
  "rebrand.ly",
  "cutt.ly",
  "tiny.cc",
  "shorturl.at",
  "rb.gy",
  "t.ly",
  "v.gd",
  "owllink.net",
  "bl.ink",
]);

export const FREE_HOSTS = [
  "github.io",
  "netlify.app",
  "vercel.app",
  "web.app",
  "firebaseapp.com",
  "blogspot.com",
  "wordpress.com",
  "weebly.com",
  "wixsite.com",
  "squarespace.com",
  "glitch.me",
  "pages.dev",
  "webflow.io",
  "000webhostapp.com",
  "herokuapp.com",
];

export const PHISHING_WORDS = [
  "login",
  "log-in",
  "signin",
  "sign-in",
  "verify",
  "verification",
  "secure",
  "update",
  "confirm",
  "password",
  "account",
  "unlock",
  "restore",
  "limited",
  "suspend",
  "billing",
  "invoice",
  "wallet",
  "recovery",
  "authenticate",
  "credential",
];

export type PhraseRule = {
  id: string;
  phrases: string[];
  tokens?: string[];
  severity: "low" | "medium" | "high";
  weight: number;
  title: string;
  detail: string;
  category: "scam" | "urgency" | "impersonation" | "privacy";
};

export const SCAM_RULES: PhraseRule[] = [
  {
    id: "digital-arrest",
    phrases: [
      "digital arrest",
      "digitally arrested",
      "virtual arrest",
      "video arrest",
      "online arrest",
    ],
    severity: "high",
    weight: 40,
    title: "Digital arrest language",
    detail:
      "Real police do not arrest people over a video call or demand money to cancel a warrant. This phrase is a hallmark of a common scam.",
    category: "impersonation",
  },
  {
    id: "law-enforcement",
    phrases: [
      "arrest warrant",
      "warrant has been issued",
      "you will be arrested",
      "legal notice",
      "court order",
      "cyber crime cell",
      "cyber cell",
      "enforcement directorate",
      "central bureau",
      "income tax raid",
      "customs department",
      "narcotics bureau",
      "interpol notice",
      "federal bureau",
      "department of justice",
      "immigration and customs",
      "social security administration",
      "internal revenue service",
    ],
    tokens: ["cbi", "ncb", "interpol"],
    severity: "high",
    weight: 28,
    title: "Impersonating officials",
    detail:
      "Scammers copy the names of police, tax, and customs agencies. A genuine officer will not demand secrecy or instant payment over a phone or chat.",
    category: "impersonation",
  },
  {
    id: "isolation",
    phrases: [
      "do not disconnect",
      "do not hang up",
      "stay on the line",
      "do not tell anyone",
      "keep this confidential",
      "this is a secret operation",
      "do not inform family",
      "mute your phone",
      "do not talk to the bank",
    ],
    severity: "high",
    weight: 26,
    title: "Tries to isolate you",
    detail:
      "Isolation is the scam. Anyone who forbids you from hanging up, calling a loved one, or checking with your bank is not protecting you.",
    category: "scam",
  },
  {
    id: "remote-access",
    phrases: [
      "anydesk",
      "teamviewer",
      "ultraviewer",
      "remote desktop",
      "allow screen share",
      "install this app to verify",
      "share your screen",
      "grant remote access",
    ],
    severity: "high",
    weight: 32,
    title: "Asks for remote access",
    detail:
      "Apps that let someone control your phone or computer are a favourite of fraudsters. Once they are in, they can move money while you watch.",
    category: "privacy",
  },
  {
    id: "otp-harvest",
    phrases: [
      "share otp",
      "share the otp",
      "tell me the otp",
      "send otp",
      "forward the code",
      "verification code is",
      "read the sms",
      "cvv number",
      "net banking password",
      "upi pin",
    ],
    tokens: ["otp"],
    severity: "high",
    weight: 30,
    title: "Asks for OTP or PIN",
    detail:
      "One-time codes and UPI PINs are the keys to your money. Banks and apps never ask you to read them out or type them into a chat.",
    category: "privacy",
  },
  {
    id: "payment-demand",
    phrases: [
      "pay immediately",
      "pay right now",
      "gift card",
      "itunes card",
      "steam card",
      "google play card",
      "wire transfer",
      "bitcoin",
      "usdt",
      "crypto wallet",
      "deposit to this account",
      "fine must be paid",
      "settlement amount",
    ],
    severity: "high",
    weight: 24,
    title: "Demands unusual payment",
    detail:
      "Gift cards, crypto, and rushed bank transfers are almost never how real fines, taxes, or courier fees work. Treat a payment demand as a stop sign.",
    category: "scam",
  },
  {
    id: "urgency",
    phrases: [
      "act now",
      "immediately",
      "within 24 hours",
      "within 2 hours",
      "last warning",
      "final notice",
      "account will be closed",
      "account will be suspended",
      "will be frozen",
      "will be sealed",
      "limited-time",
      "expires today",
      "do not ignore",
      "urgent action required",
    ],
    severity: "medium",
    weight: 12,
    title: "Pressures you to rush",
    detail:
      "Urgency is used to skip your judgement. Real institutions give you time and a way to verify on their official site or app.",
    category: "urgency",
  },
  {
    id: "kyc-threat",
    phrases: [
      "update kyc",
      "kyc pending",
      "kyc expired",
      "aadhaar suspended",
      "aadhar blocked",
      "pan card blocked",
      "account freeze",
      "re-kyc",
    ],
    severity: "medium",
    weight: 16,
    title: "KYC or ID scare",
    detail:
      "Banks do send KYC reminders — but they will not ask you to confirm passwords or pay a fee from a text link. Open the official app yourself.",
    category: "scam",
  },
  {
    id: "prize",
    phrases: [
      "you have won",
      "you've won",
      "lottery",
      "lucky winner",
      "claim your prize",
      "inheritance",
      "guaranteed returns",
      "double your money",
      "investment opportunity",
    ],
    severity: "medium",
    weight: 18,
    title: "Prize or miracle return",
    detail:
      "Unexpected winnings and guaranteed investment returns are a classic hook. If you did not enter a contest, you did not win it.",
    category: "scam",
  },
  {
    id: "job-task",
    phrases: [
      "part time job",
      "daily profit",
      "task rebate",
      "like and earn",
      "work from home offer",
      "click jobs",
      "need to recharge",
    ],
    severity: "medium",
    weight: 16,
    title: "Task or rebate job hook",
    detail:
      "Fake job apps pay a little at first, then ask you to deposit money to unlock larger ‘tasks’. That deposit is the scam.",
    category: "scam",
  },
];

export const PERMISSION_CATALOG: {
  id: string;
  label: string;
  hint: string;
  weight: number;
  highRisk: boolean;
}[] = [
  {
    id: "sms",
    label: "SMS",
    hint: "Read or send texts — can steal OTPs",
    weight: 22,
    highRisk: true,
  },
  {
    id: "accessibility",
    label: "Accessibility",
    hint: "Can tap, read, and control the whole phone",
    weight: 36,
    highRisk: true,
  },
  {
    id: "admin",
    label: "Device admin",
    hint: "Hard to uninstall; often used by lock-screen malware",
    weight: 34,
    highRisk: true,
  },
  {
    id: "overlay",
    label: "Draw over apps",
    hint: "Can fake a bank screen on top of the real one",
    weight: 24,
    highRisk: true,
  },
  {
    id: "contacts",
    label: "Contacts",
    hint: "Used to spam people you know",
    weight: 8,
    highRisk: false,
  },
  {
    id: "camera",
    label: "Camera",
    hint: "Sensitive if the app has no reason to film",
    weight: 6,
    highRisk: false,
  },
  {
    id: "microphone",
    label: "Microphone",
    hint: "Sensitive if the app has no reason to listen",
    weight: 8,
    highRisk: false,
  },
  {
    id: "location",
    label: "Location",
    hint: "Common, but still worth questioning",
    weight: 4,
    highRisk: false,
  },
  {
    id: "storage",
    label: "All files",
    hint: "Can read photos, documents, and downloads",
    weight: 10,
    highRisk: false,
  },
  {
    id: "notification",
    label: "Notification access",
    hint: "Can read OTPs that arrive as notifications",
    weight: 18,
    highRisk: true,
  },
  {
    id: "phone",
    label: "Phone / call log",
    hint: "Can see who you call",
    weight: 10,
    highRisk: false,
  },
  {
    id: "accounts",
    label: "Accounts",
    hint: "Can reach saved logins",
    weight: 16,
    highRisk: true,
  },
];

export const APP_SOURCES: { id: import("./types").AppSource; label: string }[] =
  [
    { id: "play", label: "Google Play" },
    { id: "appstore", label: "Apple App Store" },
    { id: "apk", label: "Sideloaded APK" },
    { id: "web", label: "Website download" },
    { id: "chat", label: "WhatsApp / Telegram / SMS" },
    { id: "unknown", label: "Unknown" },
  ];
